version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  backend:
    build: ./backend-ecomerce
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./backend-ecomerce:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./Ecommerce
    ports:
      - "3000:3000"
    volumes:
      - ./Ecommerce/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: